services:
  mysql:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=loopers
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
    command: --local_infile=1
    volumes:
      - mysql-8-data:/var/lib/mysql

volumes:
  mysql-8-data:

networks:
  default:
    driver: bridge